<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<h1>crear Producto</h1>

<form action="index.php?c=products&createProduct=1" method="post">
  
  <label for="name">Nombre del producto:</label><br>
  <input type="text" id="name" name="name" required><br><br>

  <label for="description">Descripción:</label><br>
  <textarea id="description" name="description" required></textarea><br><br>

  <label for="stock">Stock disponible:</label><br>
  <input type="number" id="stock" name="stock" min="0" required><br><br>

  <label for="precio">Precio (€):</label><br>
  <input type="number" id="precio" name="precio" step="0.01" min="0" required><br><br>

  <label for="imagen">Imagen (URL o nombre de archivo):</label><br>
  <input type="file" id="imagen" name="imagen" placeholder="ej: producto1.jpg" required><br><br>

  <input type="submit" value="Guardar producto">
</form>


</form>

</body>
</html>