<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<h1>Crear producto</h1>

<form action="index.php?c=products&createProduct=1" method="post" enctype="multipart/form-data">
    <input type="text" name="name" placeholder="Nombre del producto" required>
    <input type="text" name="description" placeholder="Descripción" required>
    <input type="number" name="stock" placeholder="Stock" min="0" required>
    <input type="number" name="precio" placeholder="Precio (€)" step="0.01" min="0" required>
    <input type="file" name="imagen" required>
    <input type="submit" value="Guardar producto">
</form>

</body>
</html>