<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
<h1>crear Producto</h1>

<form action="index.php?c=products" method="POST" >
    <input type="text" name="name" placeholder="nombre">
    <input type="text" name="description" placeholder="descripción">
    <input type="number" name="stock" placeholder="stock">
    <input type="submit" value="Enviar">
    

</form>

</body>
</html>