<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productos</title>
<?php
 if($_SESSION['user']){
        if ($_SESSION['user']->getAvatar()) {
        $img = $_SESSION['user']->getAvatar();
    } else $img = "avatar.jpg";

    // Mostramos la imagen y el saludo en la misma línea, dentro del mismo H3
    echo '<h3><img src="public/users/' . $img . '" width="50px" style="vertical-align: middle; margin-right: 10px;">' .
         'Hola '.$_SESSION['user']->getUsername().'. <a href="index.php?c=user&logout=1">Salir</a></h3>';
    echo '<h3>
    
       <a href="index.php?c=products&newProduct=1">Crear Producto</a><br></h3>';

       echo '<a href="index.php?c=user&edit=1">Panel de usuario</a><br>';

       echo '<a href="index.php?c=pedido">Carrito de pedidos</a><br>';

    }else{
        echo '<a href="index.php?c=user&register=1">registrarse</a><br>';
        echo '<a href="index.php?c=user&login=1">iniciar sesión</a><br>';
    }


?>

</head>
<body>
    <h2>Productos</h2>
    <?php if (count($products) > 0): ?>
        <?php foreach ($products as $product): ?>
            <div style="border: 1px solid #6c6c6cff; padding: 10px; margin: 10px 0;">
                <h3><?php echo htmlspecialchars($product->getName()); ?></h3>
                <p><strong>Descripción:</strong> <?php echo htmlspecialchars($product->getDescription()); ?></p>
                <!-- AQUI PONER LA IMAGEN -->
                <!-- Agrega aquí cualquier otra información relevante del producto -->
                <p><strong>Stock:</strong> <?php echo htmlspecialchars($product->getStock()); ?></p>
                <p><strong>Precio:</strong> <?php echo htmlspecialchars($product->getPrice()); ?>€</p>
                <?php 
                if (isset($_SESSION['user']) && is_object($_SESSION['user'])):
                    
                     echo '<a href="index.php?c=products&productId=' . $product->getId() . '">Añadir a pedidos</a>';

                    if ($_SESSION['user']->isAdmin()):
                ?>
                    <a href="index.php?delete=<?php echo $product->getId(); ?>" 
                        onclick="return confirm('¿Estás seguro de eliminar este producto?')">
                        [Eliminar Producto]
                    </a>
                <?php 
                    endif;
                endif; 
                ?>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p>No hay productos aún.</p>
    <?php endif; ?>
</body>
</html>