<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1> REGISTRER </h1>

    <form action="index.php?c=user" method="POST" enctype="multipart/form-data">
        <input type="text" name="username" placeholder="nombre de usuario">
        <input type="password" name="password" placeholder="Contraseña">
        <input type="password" name="password2" placeholder="repite la contraseña">
        <input type="file" name="image">
        <input type="submit" value="registrar">
</form>
</body>
</html>